const team = [
  //Adhwithiya
  {
    teamname: "Adhwithiya",
    name: "Your Name",
    college: "Your College name",
    batch: 2016,
    quote: "Your quote",
    photo: "https://i.ibb.co/V2LLmT7/sophists-logo-white.png",
    github: "Your github profile url",
  },
  {
    teamname: "Adhwithiya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Adhwithiya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Adhwithiya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Adhwithiya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Adhwithiya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Adhwithiya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Adhwithiya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  //Arghya
  {
    teamname: "Arghya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  //Avyakt
  {
    teamname: "Avyakt",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  //Chetak
  {
    teamname: "Chetak",
    name: "Praneeth",
    college: "RV College of Engineering",
    batch: 2019,
    quote: "If you can dream it. You can do it.",
    photo: "https://i.ibb.co/VgQKKGW/0-G0-A8528-2.jpg",
    github: "https://github.com/18praneeth",
  },
  {
    teamname: "Chetak",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Kshitij
  {
    teamname: "Kshitij",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Lakshy
  {
    teamname: "Lakshy",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Lakshy",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Lakshy",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Lakshy",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Lakshy",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Lakshy",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Lakshy",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Lakshy",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Navikaran
  {
    teamname: "Navikaran",
    name: "Bhargavi Nayak",
    college: "NMAM Institute of Technology",
    batch: 2019,
    quote: "Don't rest, start the HacktoberFest with full on zest and get the best out of it!",
    photo: "https://i.ibb.co/XL6mnp6/IMG-20201205-WA0017.jpg",
    github: "https://github.com/Bhargavi09",
  },
  {
    teamname: "Navikaran",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Ojas
  {
    teamname: "Ojas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Prakhyath
  {
    teamname: "Prakhyath",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Sadhbhav
  {
    teamname: "Sadhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Saksham
  {
    teamname: "Saksham",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Siddhanth
  {
    teamname: "Siddhanth",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Udhbhav
  {
    teamname: "Udhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Udvikas
  {
    teamname: "Udvikas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Vikalp
  {
    teamname: "Vikalp",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vikalp",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vikalp",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vikalp",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vikalp",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vikalp",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vikalp",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vikalp",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Vivaan
  {
    teamname: "Vivaan",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vivaan",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vivaan",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vivaan",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vivaan",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vivaan",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vivaan",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vivaan",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //2018 batch and Mentors

  {
    teamname: "Sushiksha",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Your Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
];
