const team = [
  // Adhwithiya

  {
    teamname: "Adhwithiya",
    name: "Srinidhi S Bhat",
    college: "Goa College of Engineering",
    batch: 2019,
    quote: "Carpe Diem",
    photo: "https://i.ibb.co/gW4ygPX/profile-img.png",
    github: "https://github.com/srinidhibhat45",
  },

  {
    teamname: "Adhwithiya",
    name: "Ananya R Prabhu",
    college: "JSS SCIENCE AND TECHNOLOGY UNIVERSITY",
    batch: 2019,
    quote: "Seize the day!",
    photo: "https://i.ibb.co/v3BdGCB/anya-profile.jpg",
    github: "https://github.com/AnanyaRPrabhu",
  },
  {
    teamname: "Adhwithiya",
    name: "Shreyas Kamath",
    college: "MANIPAL INSTITUTE OF TECHNOLOGY",
    batch: 2019,
    quote:
      "Life is not a problem to be solved, but a reality to be experienced",
    photo: "https://i.ibb.co/0KZWwMd/shreyas-profile.jpg",
    github: "https://github.com/shreyas12345678",
  },
  {
    teamname: "Adhwithiya",
    name: "K Avinash Nayak",
    college: "Manipal Institute of Technology",
    batch: 2019,
    quote: "If you can dream, you can do it",
    photo: "https://ibb.co/MB4TVtb",
    github: "https://github.com/kan12340987",
  },
  {
    teamname: "Adhwithiya",
    name: "Khushi Vaikunt Raikar",
    college: "SDM College Of Engineering and Technology Dharwad",
    batch: 2019,
    quote: "Believe in Yourself",
    photo: "https://i.ibb.co/5Mfkq0j/khushi.jpg",
    github: "https://github.com/Khushiraikar1",
  },
  {
    teamname: "Adhwithiya",
    name: "Karthik Pai",
    college: "RV College of Engineering",
    batch: 2020,
    quote: "You only live once, but if you do it right, once is enough",
    photo: "https://i.ibb.co/mc4kKhh/IMG-20210516-190611.jpg",
    github: "https://github.com/kptriescoding",
  },

  {
    teamname: "Adhwithiya",
    name: "Anusha K",
    college: "St Joseph Engineering College, Mangalore",
    batch: 2020,
    quote: "Aim impressive!!",
    photo: "https://i.ibb.co/KDFZ3nb/20191117091300-IMG-3831-JPG.jpg",
    github: "https://github.com/Anusha-K14",
  },
  {
    teamname: "Adhwithiya",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Adhwithiya",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  //Arghya
  {
    teamname: "Arghya",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Arghya",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  //Avyakt
  {
    teamname: "Avyakt",
    name: "AJAY G NAYAK",
    college: "BMS COLLEGE OF ENGINEERING",
    batch: 2019,
    quote: "This is me",
    photo: "https://i.ibb.co/B4x9WyT/photo.jpg",
    github: "https://github.com/AJ-221",
  },
  {
    teamname: "Avyakt",
    name: "AADITYA D PAI",
    college: "NATIONAL INSTITUTE of TECHNOLOGY KARNATAK, SURATHKAL",
    batch: 2019,
    quote: "Be the energy you want to attract",
    photo: "https://i.ibb.co/MpHVJnj/profile-pic-2.jpg",
    github: "https://github.com/Aadityapai",
  },
  {
    teamname: "Avyakt",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Avyakt",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  //Chetak
  {
    teamname: "Chetak",
    name: "Praneeth",
    college: "RV College of Engineering",
    batch: 2019,
    quote: "If you can dream it. You can do it.",
    photo: "https://i.ibb.co/VgQKKGW/0-G0-A8528-2.jpg",
    github: "https://github.com/18praneeth",
  },
  {
    teamname: "Chetak",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Chetak",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Kshitij
  {
    teamname: "Kshitij",
    name: "Vaishnavi Hegde",
    college: "NMAMIT, Nitte",
    batch: 2019,
    quote: "Love the Life you Live",
    photo: "https://i.ibb.co/rb5j6St/vaishnavi.jpg",
    github: "https://github.com/vaishnavihegde",
  },
  {
    teamname: "Kshitij",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Hrishikesh kamath",
    college: "BMSIT,Banglore",
    batch: 2019,
    quote: "Simplicity is the ultimate sophistication.",
    photo: "https://i.ibb.co/5hjCVWR/black.jpg",
    github: "https://github.com/hrishi-19",
  },
  {
    teamname: "Kshitij",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Kshitij",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Lakshy
  {
    teamname: "Lakshy",
    name: "Deeksha Sanu",
    college: "RV College of Engineering",
    batch: 2019,
    quote: "My goal is to be better than I used to be",
    photo: "https://i.ibb.co/R4F3fRy/Deeksha-Sanu.jpg",
    github: "https://github.com/Deeksha-Sanu",
  },
  {
    teamname: "Lakshy",
    name: "Hrishikesh K Pai",
    college: "SASTRA Deemed University",
    batch: 2020,
    quote:
      "Do the best you can until you know better. Then when you know better, do better",
    photo: "https://i.ibb.co/Y0GVbGz/IMG-20210909-WA0018.jpg",
    github: "https://https://github.com/hrishi30c",
  },
  {
    teamname: "Lakshy",
    name: "Rashmi Nayak",
    college: "KVG Ayurvedic Medical College",
    batch: 2020,
    quote: "Love yourself",
    photo: "https://i.ibb.co/tPXddJ5/Rashmi.jpg",
    github: "www.github.com",
  },
  {
    teamname: "Lakshy",
    name: "Kartik Mahale",
    college: "Shree dharmasthala majunatheshwara college of engineering and technology",
    batch: 2019,
    quote: "Look in the mirror...That's your competition",
    photo: "https://i.ibb.co/XxpV7Vx/kartik.jpg",
    github: "https://github.com/karthik7-geek",
  },
  {
    teamname: "Lakshy",
    name: "Prateeksha Vasant Pai",
    college: "Shree Dharmasthala Majunatheshwara College of Engineering and Technology",
    batch: 2019,
    quote: "Build your dreams or else someone will hire you to build their dreams",
    photo: "https://i.ibb.co/zJbjDyQ/Whats-App-Image-2021-10-08-at-6-05-59-PM.jpg",
    github: "https://github.com/PrateekshaPai",
  },
  {
    teamname: "Lakshy",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Lakshy",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Lakshy",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Navikaran
  {
    teamname: "Navikaran",
    name: "Bhargavi Nayak",
    college: "NMAM Institute of Technology",
    batch: 2019,
    quote:
      "Don't rest, start the HacktoberFest with full on zest and get the best out of it!",
    photo: "https://i.ibb.co/XL6mnp6/IMG-20201205-WA0017.jpg",
    github: "https://github.com/Bhargavi09",
  },
  {
    teamname: "Navikaran",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Navikaran",
    name: "Ashlesh shenoy",
    college: "MITE",
    batch: 2020,
    quote: "I hangout on stackoverflow ;)",
    photo: "https://i.ibb.co/9Zby0ps/Ashlesh-shenoy.jpg",
    github: "https://github.com/ashleshshenoy",
  },

  //Ojas
  {
    teamname: "Ojas",
    name: "Rishabh Naik",
    college: "Sambhram Institute of Technology",
    batch: 2019,
    quote: "Everything in this world is comparatively relative",
    photo:
      "https://sushiksha.konkanischolarship.com/media/profile_pics/PXL_20210915_073220028.PORTRAIT.jpg",
    github: "https://github.com/RishabhNaik",
  },
  {
    teamname: "Ojas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Ojas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  //Prakhyath
  {
    teamname: "Prakhyath",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Apoorva Prabhu R",
    college: "NMAM Institute of Technology, Nitte",
    batch: 2019,
    quote: "Learning is the most important currency and anyone can be rich",
    photo: "https://i.ibb.co/qFyDtWR/IMG-20201106-192353.jpg",
    github: "https://github.com/Apoorva77",
  },
  {
    teamname: "Prakhyath",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Prakhyath",
    name: "Omkar Kamat",
    college: "SDM College of Engineering and Technology",
    batch: 2020,
    quote: "Don't wait for opportunities, create your own",
    photo: "https://i.ibb.co/TwGgNDD/20210909-155711.jpg",
    github: "https://github.com/OmkarKamat869",
  },
  {
    teamname: "Prakhyath",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Sadhbhav
  {
    teamname: "Sadhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Nagaraj Pandith",
    college: "N.M.A.M. Institute of Technology",
    batch: 2020,
    quote: "Know something about everything and Everything about something!",
    photo: "https://i.ibb.co/MhTbRZ1/IMG-20210824-073615.jpg",
    github: "https://github.com/nagarajpandith",
  },
  {
    teamname: "Sadhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sadhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Saksham
  {
    teamname: "Saksham",
    name: "Keerthi Kamath",
    college: "Sahyadri College of Engineering and Management",
    batch: 2019,
    quote: "We learn together to grow together!",
    photo: "https://tinyurl.com/yvv85yku",
    github: "https://github.com/keerthi-kamath",
  },
  {
    teamname: "Saksham",
    name: "Pannag Bhaskar Kini",
    college: "B.M.S.College of Engineering",
    batch: 2020,
    quote: "It's our choices that define us more than our abilities",
    photo: "https://tinyurl.com/4kzx9vkx",
    github: "https://github.com/prongs651",
  },
  {
     teamname: "Saksham",
     name: "Kavita Satish Kamath",
     college: "Canara Engineering College",
     batch: 2019,
     quote: "You are always one decision away from a totally different life",
     photo: "https://i.ibb.co/N3x6zdq/kavita.jpg",
     github: "https://github.com/Kavita-Kamath07",
   },
  {
    teamname: "Saksham",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Saksham",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  //Siddhanth
  {
    teamname: "Siddhanth",
    name: "Shravya Mallya",
    college: "MIT Manipal",
    batch: 2019,
    quote: "You are free, and that is why you are lost.",
    photo: "https://i.ibb.co/Lx0NV4V/WKC-Photo-DP.png",
    github: "https://github.com/ShravyaMallya",
  },
  {
    teamname: "Siddhanth",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Siddhanth",
    name: "Sandesha Dsouza",
    college: "Canara Engineering College Mangalore",
    batch: 2019,
    quote: "Never dream for success, but work for it",
    photo: "https://i.ibb.co/NjrBcD7/Sandesh-copy.jpg",
    github: "https://github.com/Sandeshadsouza",
  },

  //Udhbhav
  {
    teamname: "Udhbhav",
    name: "Nima",
    college: "Sahyadri College Of Engineering and Management",
    batch: 2019,
    quote: "Live life to the fullest",
    photo: "https://i.ibb.co/m4Z8nFk/Nima.jpg",
    github: "https://github.com/Nima-ps26",
  },
  {
    teamname: "Udhbhav",
    name: "Anand C A",
    college: "Rajagiri School of Engineering Technology",
    batch: 2019,
    quote: "Don't stop until you're proud",
    photo: "https://i.ibb.co/yVPNMD1/ANAND-MAIN.png",
    github: "https://github.com/Anand911",
  },
  {
    teamname: "Udhbhav",
    name: "Prathiksha Kini",
    college: "NMAM Institute Of Technology Nitte",
    batch: 2020,
    quote: "Nothing is impossible the word itself says I'm possible!!",
    photo: "https://i.ibb.co/2nqCPmR/IMG-20210320-215906-468.jpg",
    github: "https://github.com/pkini2002",
  },
  {
    teamname: "Udhbhav",
    name: "Shreeram Bhat",
    college: "Dayananda Sagar College of Engineering",
    batch: 2019,
    quote: "Don't Settle Until, You Get It",
    photo: "https://i.ibb.co/fvzmMJj/DSC-0586.jpg",
    github: "https://github.com/bhatshreeram2001",
  },
  {
    teamname: "Udhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udhbhav",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Udvikas
  {
    teamname: "Udvikas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Prajna Prabhu",
    college: "MIT Manipal",
    batch: 2020,
    quote: "Conquer fear, everyday",
    photo:
      "https://i.ibb.co/DDr0WCV/Whats-App-Image-2021-08-08-at-10-58-35-PM.jpg",
    github: "https://github.com/Prajnaprabhu3",
  },
  {
    teamname: "Udvikas",
    name: "Reinal Antonio Carlo",
    college: "Dayananda Sagar College Of Engineering",
    batch: 2019,
    quote: "Celebrate every tiny victory",
    photo:
      "https://i.ibb.co/nsTrPy3/Whats-App-Image-2021-05-05-at-11-31-43-3.jpg",
    github: "https://github.com/ReinalCarlo",
  },
  {
    teamname: "Udvikas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Udvikas",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Vikalp
  {
    teamname: "Vikalp",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vikalp",
    name: "Vidyesh Kumar",
    college: "N.M.A.M.I.T",
    batch: 2020,
    quote: "A Machine That Converts Coffee To Code",
    photo: "https://i.ibb.co/GcTK2ZN/1630142096848.jpg",
    github: "https://github.com/vidyesh-kumar",
  },
  {
    teamname: "Vikalp",
    name: "Rohith V Kamath",
    college: "SJB Institute of Technology",
    batch: 2020,
    quote: "Action is the foundational key to all success",
    photo: "https://i.ibb.co/gZmXWWw/IMG-20210907-155420.jpgYour image url",
    github: "https://github.com/rohithvkamath",
  },
  {
    teamname: "Vikalp",
    name: "Rayesh Kamath",
    college: "Jain Engineering and Technology",
    batch: 2020,
    quote: "Talk is CHEAP, Show me the CODE",
    photo: "https://i.ibb.co/fkhcwx9/0e6cda4b-73e7-4e59-a1da-a8d2e29a809a.jpg",
    github: "https://github.com/irayesh007",
  },
  {
    teamname: "Vikalp",
    name: "Devaki Prabhu",
    college: "KLS Gogte Institute of Technology",
    batch: 2020,
    quote: "Always Be Yourself",
    photo: "https://i.ibb.co/FJXLTHD/IMG-20210314-WA0044.jpg",
    github: "https://github.com/devaki15",
  },
  {
    teamname: "Vikalp",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vikalp",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vikalp",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //Vivaan
  {
    teamname: "Vivaan",
    name: "Rajath Prabhu M",
    college: "Shri Jayachamarajendra College Of Engineering",
    batch: 2019,
    quote: "You are entitled to the actions, never to its fruits",
    photo:
      "https://media-exp1.licdn.com/dms/image/C5603AQHJYf6bBUeY1Q/profile-displayphoto-shrink_800_800/0/1616585603947?e=1638403200&v=beta&t=mcM0ZU9kaSfiBKenRQ7Mfj5gSvqPe9u7qvwMdYV5EHY",
    github: "https://github.com/RajathPrabhu221",
  },
  {
    teamname: "Vivaan",
    name: "Amulya M Kamat",
    college: "Canara Engineering College",
    batch: 2020,
    quote: "Don't limit your challenges, challenge your limits!",
    photo: "https://tinyurl.com/jzutdyz4",
    github: "https://github.com/amulya2003",
  },
  {
    teamname: "Vivaan",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vivaan",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vivaan",
    name: "Kishor Balgi",
    college: "K L S Gogte Institute of Technology",
    batch: 2020,
    quote: "Always Learning!",
    photo: "https://i.ibb.co/Fs4B3Wd/IMG20210822111231.jpg",
    github: "https://github.com/KishorBalgi",
  },
  {
    teamname: "Vivaan",
    name: "Rollin John Fernandes",
    college: "RV College of Engineering ",
    batch: 2020,
    quote: "Work hard until success tells you to stop.",
    photo: "https://i.ibb.co/6mGvmyJ/e30143a3-a2ed-4747-997a-558cebb704a2.jpg",
    github: "https://github.com/rjf04",
  },
  {
    teamname: "Vivaan",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Vivaan",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },

  //2018 batch and Mentors

  {
    teamname: "Sushiksha",
    name: "Venkatesh Prabhu",
    college: "PayPal India Pvt. Ltd",
    batch: 2011,
    quote: "I am Batman",
    photo: "https://i.ibb.co/JQkZMP1/vanky.jpg",
    github: "https://github.com/venkateshprabhu2/",
  },
  {
    teamname: "Sushiksha",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
  {
    teamname: "Sushiksha",
    name: "Name",
    college: "Your College",
    batch: 2016,
    quote: "Your quote",
    photo: "Your image url",
    github: "Your github profile url",
  },
];
